FROM node:21-alpine3.18

WORKDIR /app

COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src
COPY tools ./tools

RUN ls -a

RUN npm i && npm i -g nodemon

EXPOSE 4001

CMD [ "npm", "run", "dev" ]